apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-server
  labels:
    app: django-k8s-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-server
  template:
    metadata:
      labels:
        app: django-k8s-web-server
    spec:
      containers:
      - name: pycontainer
        image: pycontainer.azurecr.io/pycontainer/django-k8s-web
        envFrom:
          - secretRef:
              name: django-k8s-web-prod-env
        env:
          - name: PORT
            value: "8000"
        ports:
        - containerPort: 8000
          #nodeSelector:
          #"kubernetes.io/os": linux

---      
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: django-k8s-web-server

